"""End-to-end training and evaluation.

    python -m hotel_sentiment.train                 # full dataset
    python -m hotel_sentiment.train --sample 0.1    # quick run on 10% of hotels

Every number reported in the README is written by this script to
reports/metrics.json and reports/metrics.md.
"""

from __future__ import annotations

import argparse
import json
import time
from pathlib import Path

import joblib
import pandas as pd
import sklearn
from sklearn.base import clone
from sklearn.model_selection import GridSearchCV, GroupKFold, cross_val_predict, train_test_split

from . import __version__, config
from .data import build_dataset, load_raw, split_by_hotel, split_by_time
from .evaluate import (
    error_analysis,
    hotel_bootstrap_ci,
    plot_calibration,
    plot_confusion,
    plot_pr_curves,
    score_metrics,
    top_terms,
)
from .model import baselines, build_pipeline, threshold_for_recall


def _sample_hotels(df: pd.DataFrame, frac: float, seed: int) -> pd.DataFrame:
    hotels = df["Hotel_Name"].drop_duplicates().sample(frac=frac, random_state=seed)
    return df[df["Hotel_Name"].isin(hotels)].reset_index(drop=True)


def _fmt_ci(ci):
    return f"[{ci[0]:.3f}, {ci[1]:.3f}]"


def write_markdown(m: dict, path: Path) -> None:
    t = m["test"]["model"]
    ci = m["test"]["model_ci"]
    lines = [
        "# Results (generated by `python -m hotel_sentiment.train` - do not edit by hand)",
        "",
        f"Run: {m['run']['timestamp']} · rows {m['data']['final_rows']:,} · "
        f"hotels {m['data']['n_hotels']:,} · negative rate {m['data']['negative_rate']:.1%}",
        "",
        "## Held-out hotels (primary evaluation)",
        "",
        "| Model | PR-AUC | ROC-AUC |",
        "|---|---|---|",
    ]
    for name, r in m["test"]["baselines"].items():
        lines.append(f"| baseline: {name} | {r['pr_auc']:.3f} | {r['roc_auc']:.3f} |")
    lines.append(f"| **TF-IDF (1-2 gram) + LR, C={m['model']['best_C']}** | "
                 f"**{t['pr_auc']:.3f}** {_fmt_ci(ci['pr_auc_95ci'])} | **{t['roc_auc']:.3f}** |")
    lines += [
        "",
        f"## Operating point (threshold {t['threshold']:.3f}, chosen on out-of-fold training "
        f"predictions for recall >= {config.TARGET_RECALL:.0%})",
        "",
        "| Metric (negative class) | Value | 95% CI (hotel bootstrap) |",
        "|---|---|---|",
        f"| Recall | {t['recall_neg']:.3f} | {_fmt_ci(ci['recall_neg_95ci'])} |",
        f"| Precision | {t['precision_neg']:.3f} | {_fmt_ci(ci['precision_neg_95ci'])} |",
        f"| F1 | {t['f1_neg']:.3f} | |",
        f"| Share of reviews flagged | {t['flag_rate']:.1%} | |",
        f"| TP / FP / FN / TN | {t['tp']:,} / {t['fp']:,} / {t['fn']:,} / {t['tn']:,} | |",
        "",
        "## Robustness",
        "",
        "PR-AUC and precision rise with the share of negatives in the test set, so compare",
        "each row against its own no-skill rate (= negative rate).",
        "",
        "| Split | Negative rate (no-skill PR-AUC) | PR-AUC | ROC-AUC | Recall @ threshold | Precision @ threshold |",
        "|---|---|---|---|---|---|",
    ]
    for name, r in m["robustness"].items():
        lines.append(f"| {name} | {r['prevalence']:.3f} | {r['pr_auc']:.3f} | {r['roc_auc']:.3f} | "
                     f"{r['recall_neg']:.3f} | {r['precision_neg']:.3f} |")
    path.write_text("\n".join(lines) + "\n")


def main(argv=None) -> dict:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--data", type=Path, default=config.DATA_PATH)
    ap.add_argument("--sample", type=float, default=1.0, help="fraction of HOTELS to use (quick runs)")
    ap.add_argument("--n-boot", type=int, default=300)
    ap.add_argument("--n-jobs", type=int, default=-1)
    ap.add_argument("--reports-dir", type=Path, default=config.REPORTS_DIR)
    ap.add_argument("--model-path", type=Path, default=config.MODEL_PATH)
    args = ap.parse_args(argv)

    t0 = time.time()
    reports, figs = args.reports_dir, args.reports_dir / "figures"
    figs.mkdir(parents=True, exist_ok=True)
    args.model_path.parent.mkdir(parents=True, exist_ok=True)

    # 1. Data -------------------------------------------------------------------
    df, audit = build_dataset(load_raw(args.data))
    if args.sample < 1.0:
        df = _sample_hotels(df, args.sample, config.RANDOM_STATE)
        audit.update(sampled_hotel_fraction=args.sample, final_rows=int(len(df)),
                     negative_rate=float(df["is_negative"].mean()),
                     n_hotels=int(df["Hotel_Name"].nunique()))
    print(json.dumps(audit, indent=2))

    train, test = split_by_hotel(df)
    assert not set(train.Hotel_Name) & set(test.Hotel_Name), "hotel leakage between train and test"
    Xtr, ytr, gtr = train["text"], train["is_negative"], train["Hotel_Name"]
    Xte, yte = test["text"], test["is_negative"]
    cv = GroupKFold(n_splits=config.CV_FOLDS)

    # 2. Tune C with hotel-grouped CV on TRAIN only ------------------------------
    search = GridSearchCV(build_pipeline(), {"clf__C": config.C_GRID},
                          scoring="average_precision", cv=cv, n_jobs=args.n_jobs)
    search.fit(Xtr, ytr, groups=gtr)
    best_C = search.best_params_["clf__C"]
    print(f"best C = {best_C}  (CV PR-AUC {search.best_score_:.3f})")

    # 3. Threshold from out-of-fold TRAIN predictions -----------------------------
    oof = cross_val_predict(build_pipeline(C=best_C), Xtr, ytr, groups=gtr, cv=cv,
                            method="predict_proba", n_jobs=args.n_jobs)[:, 1]
    threshold = threshold_for_recall(ytr, oof)

    # 4. Final model = refit on all training hotels; evaluate once on test -------
    model = search.best_estimator_
    p_test = model.predict_proba(Xte)[:, 1]
    test_metrics = score_metrics(yte, p_test, threshold)
    ci = hotel_bootstrap_ci(test, p_test, threshold, n_boot=args.n_boot)

    base_results, curves = {}, {"TF-IDF + LR": p_test}
    for name, est in baselines().items():
        est.fit(Xtr, ytr)
        p = est.predict_proba(Xte)[:, 1]
        base_results[name] = score_metrics(yte, p, 0.5)
        if name in ("review_length", "tfidf_stopwords_removed"):
            curves[name] = p

    # 5. Robustness: random-row split (optimistic) and time split (drift) --------
    robustness = {"held-out hotels (primary)": test_metrics}
    rtr, rte = train_test_split(df, test_size=config.TEST_SIZE, random_state=config.RANDOM_STATE,
                                stratify=df["is_negative"])
    m_rand = clone(build_pipeline(C=best_C)).fit(rtr["text"], rtr["is_negative"])
    robustness["random rows (leaks hotel context)"] = score_metrics(
        rte["is_negative"], m_rand.predict_proba(rte["text"])[:, 1], threshold)
    ttr, tte = split_by_time(df)
    if len(ttr) and len(tte) and tte["is_negative"].nunique() == 2:
        m_time = clone(build_pipeline(C=best_C)).fit(ttr["text"], ttr["is_negative"])
        robustness["most recent 20% of dates"] = score_metrics(
            tte["is_negative"], m_time.predict_proba(tte["text"])[:, 1], threshold)

    # 6. Artefacts -----------------------------------------------------------------
    joblib.dump({
        "pipeline": model,
        "threshold": threshold,
        "label_definition": {"negative_if_score_le": config.NEGATIVE_MAX_SCORE,
                             "positive_if_score_ge": config.POSITIVE_MIN_SCORE},
        "version": __version__,
        "sklearn_version": sklearn.__version__,
    }, args.model_path)

    top_terms(model).to_csv(reports / "top_terms.csv", index=False)
    error_analysis(test, p_test, threshold).to_csv(reports / "error_analysis.csv", index=False)
    plot_pr_curves(yte.to_numpy(), curves, figs / "pr_curve.png")
    plot_confusion(test_metrics, figs / "confusion_matrix.png")
    plot_calibration(yte.to_numpy(), p_test, figs / "calibration.png")

    metrics = {
        "run": {"timestamp": time.strftime("%Y-%m-%d %H:%M"), "seconds": round(time.time() - t0, 1),
                "version": __version__, "sklearn": sklearn.__version__, "args": {k: str(v) for k, v in vars(args).items()}},
        "data": audit,
        "split": {"train_rows": len(train), "test_rows": len(test),
                  "train_hotels": int(train.Hotel_Name.nunique()), "test_hotels": int(test.Hotel_Name.nunique())},
        "model": {"best_C": best_C, "cv_pr_auc": float(search.best_score_),
                  "cv_results": {str(c): float(s) for c, s in zip(config.C_GRID, search.cv_results_["mean_test_score"])},
                  "threshold": threshold, "target_recall": config.TARGET_RECALL},
        "test": {"model": test_metrics, "model_ci": ci, "baselines": base_results},
        "robustness": robustness,
    }
    (reports / "metrics.json").write_text(json.dumps(metrics, indent=2))
    write_markdown(metrics, reports / "metrics.md")
    print((reports / "metrics.md").read_text())
    print(f"Saved model -> {args.model_path}")
    return metrics


if __name__ == "__main__":
    main()
